### ISSUE TITLE
Build Fails with Blue Green but not Travis Deploy

### ISSUE THREAD

**Issue by Snugug** [18F/cf-blue-green#20]
Using CF Blue Green Travis, my build fails when deploying through Travis (`node-gyp` problem with `bcrypt`) but if I use Travis's [built in Cloud Foundry deploy](http://docs.travis-ci.com/user/deployment/cloudfoundry/), it works fine. Same Node version, same NPM version.

Any thoughts as to why this may be?

**Comment by afeld** [comment]
Can you paste the relevant output from the logs? Excited to hear you're trying it!

**Comment by Snugug** [comment]
Oh! Hey!

```
-----> Building dependencies
       Installing node modules
       > bcrypt@0.8.5 install /tmp/staged/app/node_modules/bcrypt
       > node-gyp rebuild
       make: Entering directory `/tmp/staged/app/node_modules/bcrypt/build'
         CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
       make: g++-4.8: Command not found
       make: *** [Release/obj.target/bcrypt_lib/src/blowfish.o] Error 127
       make: Leaving directory `/tmp/staged/app/node_modules/bcrypt/build'
       gyp ERR! build error 
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! stack     at ChildProcess.onExit (/tmp/staged/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
       gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
       gyp ERR! System Linux 3.16.0-33-generic
       gyp ERR! command "node" "/tmp/staged/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
       gyp ERR! cwd /tmp/staged/app/node_modules/bcrypt
       gyp ERR! node -v v0.12.7
       gyp ERR! node-gyp -v v2.0.1
       gyp ERR! not ok 
       npm WARN optional dep failed, continuing fsevents@0.3.8
       npm ERR! Linux 3.16.0-33-generic
       npm ERR! argv "/tmp/staged/app/vendor/node/bin/node" "/tmp/staged/app/vendor/node/bin/npm" "install" "--unsafe-perm" "--quiet" "--userconfig" "/tmp/staged/app/.npmrc"
       npm ERR! node v0.12.7
       npm ERR! npm  v2.11.3
       npm ERR! code ELIFECYCLE
       npm ERR! bcrypt@0.8.5 install: `node-gyp rebuild`
       npm ERR! Exit status 1
       npm ERR! 
       npm ERR! Failed at the bcrypt@0.8.5 install script 'node-gyp rebuild'.
       npm ERR! This is most likely a problem with the bcrypt package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     node-gyp rebuild
       npm ERR! You can get their info via:
       npm ERR!     npm owner ls bcrypt
       npm ERR! There is likely additional logging output above.
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/staged/app/npm-debug.log
-----> Build failed
```

That's not a very helpful error, mind you but it's a start.

I notice two differences between the this and the default Travis deploy. The first is that the Travis deploy makes use of the cached `node_modules` folder if it exists, and the second is how the command line tools are installed. Check out [how Travis does it](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/cloud_foundry.rb#L6).

I'm going to play around with doing it their way this morning and if it works I'm going to issue a PR if that's cool!

**Comment by Snugug** [comment]
I tried it out, `latest` doesn't work (error as you describe) but `master` seems to have a fix in it, so just waiting on a new release

**Comment by afeld** [comment]
I don't quite understand the backtrace from above...is that happening in the build or the deploy step? Can you paste the full log? `cf-blue-green` doesn't have any node dependencies, so seems like the issues installing `bcrypt` are unrelated.

> the Travis deploy makes use of the cached `node_modules` folder if it exists

Ah. We might want to suggest that people [`skip_cleanup`](http://docs.travis-ci.com/user/deployment/#Uploading-Files)... @dhcole sound reasonable?

> `master` seems to have a fix in it

Thanks for the reminder...will update the README.

>  I'm going to issue a PR

:tada:

**Comment by dhcole** [comment]
Yea, that makes sense. Prevents building the site twice (once during tests,
and once during deployment)

**Comment by Snugug** [comment]
@afeld It happens during `deploy`

```
Deploying application
Selecting previously unselected package cf-cli.
(Reading database ... 71420 files and directories currently installed.)
Unpacking cf-cli (from temp.deb) ...
Setting up cf-cli (6.12.1) ...
Setting api endpoint to https://my.api.endpoint/...
OK

API endpoint:   https://my.api.endpoint (API version: 2.27.0)   
Not logged in. Use 'cf login' to log in.
API endpoint: https://my.api.endpoint
Authenticating...
OK
Targeted org watson
Targeted space dev

API endpoint:   https://my.api.endpoint (API version: 2.27.0)   
User:           my@email.com   
Org:            watson   
Space:          dev   
+'[' 1 -ne 1 ']'
+BLUE=my-app
+GREEN=my-app-B
++cf --version
+CF_VERSION='cf version 6.12.1-56792aa-2015-07-06T22:48:00+00:00'
+[[ cf version 6.12.1-56792aa-2015-07-06T22:48:00+00:00 != *\6\.\1\2\.\0\-* ]]
+[[ cf version 6.12.1-56792aa-2015-07-06T22:48:00+00:00 != *\6\.\1\2\.\1\-* ]]
++mktemp -t my-app_manifest.XXXXXXXXXX
+MANIFEST=/tmp/my-app_manifest.tN4PLOQB1p
+cf create-app-manifest my-app -p /tmp/my-app_manifest.tN4PLOQB1p
Creating an app manifest from current settings of app Holmes ...
OK
Manifest file created successfully at /tmp/my-app_manifest.tN4PLOQB1p
+trap on_fail ERR
++cat /tmp/my-app_manifest.tN4PLOQB1p
++awk '{print $2}'
++grep domain:
+DOMAIN=w3ibm.mybluemix.net
+cf push my-app-B -f /tmp/my-app_manifest.tN4PLOQB1p -n my-app-B
Using manifest file /tmp/my-app_manifest.tN4PLOQB1p
Updating app my-app-B in org watson / space dev as my@email.com...
OK
Using route my-app-B.w3ibm.mybluemix.net
Uploading my-app-B...
Uploading app files from: /home/travis/build/username/my-app
Uploading 20.4K, 29 files
Done uploading
OK
Binding service my-app to app my-app-B in org watson / space dev as my@email.com...
OK
Binding service email to app my-app-B in org watson / space dev as my@email.com...
OK
Stopping app my-app-B in org watson / space dev as my@email.com...
OK
Starting app my-app-B in org watson / space dev as my@email.com...
-----> Downloaded app package (12K)
-----> IBM SDK for Node.js Buildpack v2.3-20150720-1448
       Based on Cloud Foundry Node.js Buildpack v64
-----> Reading application state
       package.json...
       build directory...
       cache directory...
       environment variables...
       Node engine range:   ^0.12
       Npm engine:          unspecified
       Start mechanism:     npm start
       node_modules source: package.json
       node_modules cached: false
       NPM_CONFIG_PRODUCTION=true
       NODE_MODULES_CACHE=true
-----> Installing binaries
       Resolving node version ^0.12 via 'node-version-resolver'
       Installing IBM SDK for Node.js (0.12.7) from cache
       Using default npm version: 2.11.3
-----> Checking and configuring service extensions before installing dependencies
-----> Building dependencies
       Installing node modules
       > bcrypt@0.8.5 install /tmp/staged/app/node_modules/bcrypt
       > node-gyp rebuild
       make: Entering directory `/tmp/staged/app/node_modules/bcrypt/build'
         CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
       make: g++-4.8: Command not found
       make: *** [Release/obj.target/bcrypt_lib/src/blowfish.o] Error 127
       make: Leaving directory `/tmp/staged/app/node_modules/bcrypt/build'
       gyp ERR! build error 
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! stack     at ChildProcess.onExit (/tmp/staged/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
       gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
       gyp ERR! System Linux 3.16.0-33-generic
       gyp ERR! command "node" "/tmp/staged/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
       gyp ERR! cwd /tmp/staged/app/node_modules/bcrypt
       gyp ERR! node -v v0.12.7
       gyp ERR! node-gyp -v v2.0.1
       gyp ERR! not ok 
       npm WARN optional dep failed, continuing fsevents@0.3.8
       npm ERR! Linux 3.16.0-33-generic
       npm ERR! argv "/tmp/staged/app/vendor/node/bin/node" "/tmp/staged/app/vendor/node/bin/npm" "install" "--unsafe-perm" "--quiet" "--userconfig" "/tmp/staged/app/.npmrc"
       npm ERR! node v0.12.7
       npm ERR! npm  v2.11.3
       npm ERR! code ELIFECYCLE
       npm ERR! bcrypt@0.8.5 install: `node-gyp rebuild`
       npm ERR! Exit status 1
       npm ERR! 
       npm ERR! Failed at the bcrypt@0.8.5 install script 'node-gyp rebuild'.
       npm ERR! This is most likely a problem with the bcrypt package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     node-gyp rebuild
       npm ERR! You can get their info via:
       npm ERR!     npm owner ls bcrypt
       npm ERR! There is likely additional logging output above.
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/staged/app/npm-debug.log
-----> Build failed
Staging failed: Buildpack compilation step failed
FAILED
BuildpackCompileFailed
```

Also, it seems as if if that is indeed the fix in `master`, that `latest` doesn't have it yet, so no PR yet :cry:. Moving to how Travis does it would also make mean changes to how the core file works, and it's not much of a difference at the end of the day

**Comment by Snugug** [comment]
They've rolled a [v6.12.4](https://github.com/cloudfoundry/cli/releases/tag/v6.12.4), but no releases yet. Once out, hopefully that'll solve my issue!

**Comment by afeld** [comment]
The [downloads](https://github.com/cloudfoundry/cli#downloads) are now available...mind giving it another try with `cf-blue-green` v0.2.1+?

**Comment by Snugug** [comment]
Nope, still not working, but it's looking more and more like it's just an absolute pain in the ass to build Bcrypt

**Comment by Snugug** [comment]
Moving to bcryptjs from bcrypt (where no native bindings need to be built) fixed this issue

**Comment by Snugug** [comment]
Switching to that makes all the things work as expected. Thanks!
